defaults:
  - env_vars: env_vars
  - _self_

seed: 42
window_size: 20
goal_window_size: 0
eval_window_size: 5
# batch_size: 1024
batch_size: 200
epochs: 300
eval_freq: 10
eval_on_env_freq: 20
num_env_evals: 20
num_final_evals: 20
num_final_eval_per_goal: 5
action_window_size: 1
sequentially_select: true
# vqvae_load_dir: /home/irmak//Workspace/third-person-manipulation/out/checkpoints/vqbet/2024-05-23/17-18-40/scarlet-leaf-50/trained_vqvae.pt
# vqvae_load_dir: /home/yinlong/Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-04/17-00-01/giddy-smoke-57/trained_vqvae.pt
# vqvae_load_dir: /home/yinlong//Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-06/16-58-44/Offline/trained_vqvae.pt
# vqvae_load_dir: /home/yinlong//Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-06/17-14-03/Offline/trained_vqvae.pt
# vqvae_load_dir: /home/yinlong/Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-06/17-16-25/summer-microwave-60/trained_vqvae.pt
# vqvae_load_dir: /home/yinlong/Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-07/15-38-05/honest-paper-67/trained_vqvae.pt
# vqvae_load_dir: /home/yinlong/Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-07/16-17-49/comfy-darkness-70/trained_vqvae.pt
# vqvae_load_dir: /home/yinlong/Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-11/13-07-18/smart-pine-73/trained_vqvae.pt
vqvae_load_dir: /home/yinlong/Desktop/third-person-manipulation/out/checkpoints/vqbet/2024-06-11/15-38-55/glamorous-plasma-77/trained_vqvae.pt
goal_dim: 0
view_num: 2 
train_fraction: 0.6
visual_input: false

wandb:
  project: "vq-bet"
  entity: ${env_vars.wandb_entity}

device: 0
optim:
  lr: 5.5e-5
  weight_decay: 2e-4
  betas: [0.9, 0.999]

env:
  gym:
    _target_: kitchen_env.KitchenWrapper
    id: kitchen-v0
    env:
      _target_: gym.make
      id: kitchen-v0
    # visual_input: ${visual_input}
  # obs_dim: 512
  obs_dim: 752
  act_dim: 24
  goal_dim: 0


data:
  _target_: dataset.get_retargeting_train_val
  data_directory: ${env_vars.datasets.retargeting}
  model_type: {"model":dynamics,"ckpt":39,"param":'100_flipped_pretrained'}
  train_fraction: ${train_fraction}
  window_size: ${window_size}
  future_seq_len: ${goal_window_size}
  min_future_sep: ${action_window_size}
  action_window_size: ${action_window_size}
  vqbet_get_future_action_chunk: true
  # clipping_index_list: ${clipping_index_list}
  view_num: ${view_num}
  concat_obs_action: true

save_every: 10
save_path: "${env_vars.save_path}/checkpoints/${env.gym.id}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
load_path: null

model:
  _target_: vq_behavior_transformer.BehaviorTransformer
  # obs_dim: ${env.obs_dim}
  # obs_dim: 512
  obs_dim: 752
  act_dim: ${env.act_dim}
  goal_dim: ${env.goal_dim}
  obs_window_size: ${window_size}
  act_window_size: ${action_window_size}
  sequentially_select: ${sequentially_select}
  visual_input: false
  gpt_model:
    _target_: vq_behavior_transformer.GPT
    config:
      _target_: vq_behavior_transformer.GPTConfig
      block_size: 110
      # input_dim: ${env.obs_dim}
      # input_dim: 512
      input_dim: 752 
      n_layer: 6
      n_head: 6
      n_embd: 120
  vqvae_model:
    _target_: vqvae.VqVae
    # obs_dim: 512
    obs_dim: 752
    input_dim_h: ${action_window_size}
    input_dim_w: ${env.act_dim}
    n_latent_dims: 512
    vqvae_n_embed: 16
    vqvae_groups: 2
    eval: true
    device: ${device}
    load_dir: ${vqvae_load_dir}
  offset_loss_multiplier: 0.1
  secondary_code_multiplier: 3

# goal_fn:
#   _target_: retargeting_env.get_goal_fn
#   data_directory: ${env_vars.datasets.retargeting}
#   goal_conditional: ${data.goal_conditional}
#   seed: ${seed}
#   train_fraction: 0.95
#   goal_seq_len: ${goal_window_size}
#   unconditional: true
